// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/Commands.proto

package pbapi // import "github.com/KrishnaIyer/xdot-helper/pkg/pbapi"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Command is equivalent to a single AT command as defined in the XDOT spec.
type Command struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	Request              string   `protobuf:"bytes,3,opt,name=request" json:"request,omitempty"`
	Arguments            string   `protobuf:"bytes,4,opt,name=arguments" json:"arguments,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}
func (*Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_Commands_0d4cc5b5d956df00, []int{0}
}
func (m *Command) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command.Unmarshal(m, b)
}
func (m *Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command.Marshal(b, m, deterministic)
}
func (dst *Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command.Merge(dst, src)
}
func (m *Command) XXX_Size() int {
	return xxx_messageInfo_Command.Size(m)
}
func (m *Command) XXX_DiscardUnknown() {
	xxx_messageInfo_Command.DiscardUnknown(m)
}

var xxx_messageInfo_Command proto.InternalMessageInfo

func (m *Command) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Command) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Command) GetRequest() string {
	if m != nil {
		return m.Request
	}
	return ""
}

func (m *Command) GetArguments() string {
	if m != nil {
		return m.Arguments
	}
	return ""
}

type Response struct {
	Response             []byte   `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_Commands_0d4cc5b5d956df00, []int{1}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetResponse() []byte {
	if m != nil {
		return m.Response
	}
	return nil
}

func init() {
	proto.RegisterType((*Command)(nil), "Command")
	proto.RegisterType((*Response)(nil), "Response")
}

func init() { proto.RegisterFile("api/Commands.proto", fileDescriptor_Commands_0d4cc5b5d956df00) }

var fileDescriptor_Commands_0d4cc5b5d956df00 = []byte{
	// 195 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0x47, 0x15, 0x88, 0x48, 0x72, 0x30, 0x79, 0xb2, 0x10, 0x43, 0x94, 0x01, 0x31, 0x40, 0x3c,
	0xf0, 0x0d, 0x60, 0x42, 0x6c, 0x19, 0xbb, 0x39, 0xc9, 0x29, 0xb1, 0x5a, 0xdb, 0xd7, 0xb3, 0xa3,
	0xb6, 0xdf, 0xbe, 0x92, 0x95, 0xfe, 0xd9, 0x7e, 0xef, 0xbd, 0xe1, 0x74, 0x20, 0x34, 0x19, 0xf5,
	0xeb, 0xad, 0xd5, 0x6e, 0x0c, 0x2d, 0xb1, 0x8f, 0xbe, 0x39, 0x40, 0xb1, 0x1a, 0x21, 0x20, 0x77,
	0xda, 0xa2, 0xcc, 0xea, 0xec, 0xa3, 0xea, 0xd2, 0x16, 0x35, 0x3c, 0x8f, 0x18, 0x06, 0x36, 0x14,
	0x8d, 0x77, 0xf2, 0x21, 0xa5, 0x7b, 0x25, 0x24, 0x14, 0x8c, 0xfb, 0x05, 0x43, 0x94, 0x8f, 0xa9,
	0x5e, 0x50, 0xbc, 0x41, 0xa5, 0x79, 0x5a, 0x2c, 0xba, 0x18, 0x64, 0x9e, 0xda, 0x4d, 0x34, 0xef,
	0x50, 0x76, 0x18, 0xc8, 0xbb, 0x80, 0xe2, 0x15, 0x4a, 0x5e, 0x77, 0xba, 0xfe, 0xd2, 0x5d, 0xf9,
	0xa7, 0xdd, 0x7c, 0x4e, 0x26, 0xce, 0x4b, 0xdf, 0x0e, 0xde, 0xaa, 0x7f, 0x36, 0x61, 0x76, 0xfa,
	0xef, 0x84, 0xac, 0x8e, 0xa3, 0x8f, 0x5f, 0x33, 0xee, 0x08, 0x59, 0xd1, 0x76, 0x52, 0xd4, 0x6b,
	0x32, 0xfd, 0x53, 0xfa, 0xeb, 0xfb, 0x1c, 0x00, 0x00, 0xff, 0xff, 0xd0, 0xb9, 0xe5, 0xcf, 0xed,
	0x00, 0x00, 0x00,
}
