// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/command.proto

package pbapi // import "github.com/KrishnaIyer/xdot-helper/pkg/pbapi"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Command is equivalent to a single AT command as defined in the ATcommand spec.
type Command struct {
	// name is the user defined name of the AT command.
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// description is a simple function description.
	Description string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	// request is the actual request sent to the device.
	Request string `protobuf:"bytes,3,opt,name=request" json:"request,omitempty"`
	// arguments are optional arguments used for some commands.
	Arguments string `protobuf:"bytes,4,opt,name=arguments" json:"arguments,omitempty"`
	// wait_period is the amount of time to wait for a response.
	WaitPeriod int32 `protobuf:"varint,5,opt,name=wait_period,json=waitPeriod" json:"wait_period,omitempty"`
	// lines_in_response is the expected lines in the response for each  command.
	LinesInResponse      int32    `protobuf:"varint,6,opt,name=lines_in_response,json=linesInResponse" json:"lines_in_response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}
func (*Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_command_abb4e08afd69231b, []int{0}
}
func (m *Command) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command.Unmarshal(m, b)
}
func (m *Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command.Marshal(b, m, deterministic)
}
func (dst *Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command.Merge(dst, src)
}
func (m *Command) XXX_Size() int {
	return xxx_messageInfo_Command.Size(m)
}
func (m *Command) XXX_DiscardUnknown() {
	xxx_messageInfo_Command.DiscardUnknown(m)
}

var xxx_messageInfo_Command proto.InternalMessageInfo

func (m *Command) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Command) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Command) GetRequest() string {
	if m != nil {
		return m.Request
	}
	return ""
}

func (m *Command) GetArguments() string {
	if m != nil {
		return m.Arguments
	}
	return ""
}

func (m *Command) GetWaitPeriod() int32 {
	if m != nil {
		return m.WaitPeriod
	}
	return 0
}

func (m *Command) GetLinesInResponse() int32 {
	if m != nil {
		return m.LinesInResponse
	}
	return 0
}

// Result is the structure containing information on the command execution result.
type Result struct {
	// request is the command that was executed.
	Request string `protobuf:"bytes,1,opt,name=request" json:"request,omitempty"`
	// response_code is either `OK` or `ERROR`, which is received from the device upon executing the command.
	ResponseCode string `protobuf:"bytes,2,opt,name=response_code,json=responseCode" json:"response_code,omitempty"`
	// response is the string recevied from the device.
	Response string `protobuf:"bytes,3,opt,name=response" json:"response,omitempty"`
	// error is the error message (if any) during the execution of the command.
	// This is different from an `ERROR` response_code, where the command was actually executed and the device returned an error.
	Error                string   `protobuf:"bytes,4,opt,name=error" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_command_abb4e08afd69231b, []int{1}
}
func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (dst *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(dst, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetRequest() string {
	if m != nil {
		return m.Request
	}
	return ""
}

func (m *Result) GetResponseCode() string {
	if m != nil {
		return m.ResponseCode
	}
	return ""
}

func (m *Result) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

func (m *Result) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*Command)(nil), "api.Command")
	proto.RegisterType((*Result)(nil), "api.Result")
}

func init() { proto.RegisterFile("api/command.proto", fileDescriptor_command_abb4e08afd69231b) }

var fileDescriptor_command_abb4e08afd69231b = []byte{
	// 279 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xcd, 0x4e, 0xeb, 0x30,
	0x10, 0x85, 0x95, 0xdb, 0xbf, 0xdb, 0x29, 0x08, 0xd5, 0x62, 0x61, 0x21, 0x24, 0xa2, 0xb2, 0xa9,
	0x10, 0x24, 0x0b, 0xde, 0x80, 0xae, 0x2a, 0x36, 0x28, 0x4b, 0x36, 0x91, 0x13, 0x8f, 0x12, 0x8b,
	0xc4, 0x36, 0x63, 0x47, 0xd0, 0xf7, 0xe3, 0xc1, 0x10, 0x4e, 0x52, 0xca, 0xce, 0xe7, 0xfb, 0x2c,
	0x7b, 0xce, 0xc0, 0x5a, 0x58, 0x95, 0x96, 0xa6, 0x6d, 0x85, 0x96, 0x89, 0x25, 0xe3, 0x0d, 0x9b,
	0x08, 0xab, 0x36, 0x5f, 0x11, 0x2c, 0x76, 0x3d, 0x66, 0x0c, 0xa6, 0x5a, 0xb4, 0xc8, 0xa3, 0x38,
	0xda, 0x2e, 0xb3, 0x70, 0x66, 0x31, 0xac, 0x24, 0xba, 0x92, 0x94, 0xf5, 0xca, 0x68, 0xfe, 0x2f,
	0xa8, 0x53, 0xc4, 0x38, 0x2c, 0x08, 0xdf, 0x3b, 0x74, 0x9e, 0x4f, 0x82, 0x1d, 0x23, 0xbb, 0x86,
	0xa5, 0xa0, 0xaa, 0x6b, 0x51, 0x7b, 0xc7, 0xa7, 0xc1, 0xfd, 0x02, 0x76, 0x03, 0xab, 0x0f, 0xa1,
	0x7c, 0x6e, 0x91, 0x94, 0x91, 0x7c, 0x16, 0x47, 0xdb, 0x59, 0x06, 0x3f, 0xe8, 0x25, 0x10, 0x76,
	0x07, 0xeb, 0x46, 0x69, 0x74, 0xb9, 0xd2, 0x39, 0xa1, 0xb3, 0x46, 0x3b, 0xe4, 0xf3, 0x70, 0xed,
	0x22, 0x88, 0xbd, 0xce, 0x06, 0xbc, 0x39, 0xc0, 0x3c, 0x43, 0xd7, 0x35, 0xfe, 0x74, 0x9c, 0xe8,
	0xef, 0x38, 0xb7, 0x70, 0x3e, 0x3e, 0x93, 0x97, 0x46, 0xe2, 0x50, 0xe6, 0x6c, 0x84, 0x3b, 0x23,
	0x91, 0x5d, 0xc1, 0xff, 0xe3, 0x5f, 0x7d, 0x9d, 0x63, 0x66, 0x97, 0x30, 0x43, 0x22, 0x43, 0x43,
	0x97, 0x3e, 0x3c, 0x25, 0xaf, 0xf7, 0x95, 0xf2, 0x75, 0x57, 0x24, 0xa5, 0x69, 0xd3, 0x67, 0x52,
	0xae, 0xd6, 0x62, 0x7f, 0x40, 0x4a, 0x3f, 0xa5, 0xf1, 0x0f, 0x35, 0x36, 0x16, 0x29, 0xb5, 0x6f,
	0x55, 0x6a, 0x0b, 0x61, 0x55, 0x31, 0x0f, 0xdb, 0x7f, 0xfc, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xcf,
	0xbb, 0x83, 0x33, 0x92, 0x01, 0x00, 0x00,
}
