// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/command.proto

package pbapi // import "github.com/KrishnaIyer/xdot-helper/pkg/pbapi"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Result_ResCode int32

const (
	Result_NONE  Result_ResCode = 0
	Result_OK    Result_ResCode = 1
	Result_ERROR Result_ResCode = 2
)

var Result_ResCode_name = map[int32]string{
	0: "NONE",
	1: "OK",
	2: "ERROR",
}
var Result_ResCode_value = map[string]int32{
	"NONE":  0,
	"OK":    1,
	"ERROR": 2,
}

func (x Result_ResCode) String() string {
	return proto.EnumName(Result_ResCode_name, int32(x))
}
func (Result_ResCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_command_d8b4563e9c0e3d21, []int{1, 0}
}

// Command is equivalent to a single AT command as defined in the ATcommand spec.
type Command struct {
	// name is the user defined name of the AT command.
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// description is a simple function description.
	Description string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	// request is the actual request sent to the device.
	Request string `protobuf:"bytes,3,opt,name=request" json:"request,omitempty"`
	// wait_period is the amount of time to wait for a response.
	WaitPeriod int32 `protobuf:"varint,4,opt,name=wait_period,json=waitPeriod" json:"wait_period,omitempty"`
	// lines_in_response is the expected lines in the response for each  command.
	LinesInResponse      int32    `protobuf:"varint,5,opt,name=lines_in_response,json=linesInResponse" json:"lines_in_response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}
func (*Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_command_d8b4563e9c0e3d21, []int{0}
}
func (m *Command) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command.Unmarshal(m, b)
}
func (m *Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command.Marshal(b, m, deterministic)
}
func (dst *Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command.Merge(dst, src)
}
func (m *Command) XXX_Size() int {
	return xxx_messageInfo_Command.Size(m)
}
func (m *Command) XXX_DiscardUnknown() {
	xxx_messageInfo_Command.DiscardUnknown(m)
}

var xxx_messageInfo_Command proto.InternalMessageInfo

func (m *Command) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Command) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Command) GetRequest() string {
	if m != nil {
		return m.Request
	}
	return ""
}

func (m *Command) GetWaitPeriod() int32 {
	if m != nil {
		return m.WaitPeriod
	}
	return 0
}

func (m *Command) GetLinesInResponse() int32 {
	if m != nil {
		return m.LinesInResponse
	}
	return 0
}

// Result is the structure containing information on the command execution result.
type Result struct {
	// request is the command that was executed.
	Request string `protobuf:"bytes,1,opt,name=request" json:"request,omitempty"`
	// response_code is either `OK` or `ERROR`, which is received from the device upon executing the command.
	ResponseCode Result_ResCode `protobuf:"varint,2,opt,name=response_code,json=responseCode,enum=api.Result_ResCode" json:"response_code,omitempty"`
	// response is the string recevied from the device.
	Response             string   `protobuf:"bytes,3,opt,name=response" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_command_d8b4563e9c0e3d21, []int{1}
}
func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (dst *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(dst, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetRequest() string {
	if m != nil {
		return m.Request
	}
	return ""
}

func (m *Result) GetResponseCode() Result_ResCode {
	if m != nil {
		return m.ResponseCode
	}
	return Result_NONE
}

func (m *Result) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

func init() {
	proto.RegisterType((*Command)(nil), "api.Command")
	proto.RegisterType((*Result)(nil), "api.Result")
	proto.RegisterEnum("api.Result_ResCode", Result_ResCode_name, Result_ResCode_value)
}

func init() { proto.RegisterFile("api/command.proto", fileDescriptor_command_d8b4563e9c0e3d21) }

var fileDescriptor_command_d8b4563e9c0e3d21 = []byte{
	// 302 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0x4d, 0x4f, 0x3a, 0x31,
	0x10, 0xc6, 0xff, 0xe5, 0x9d, 0xe1, 0xaf, 0x42, 0xbd, 0x6c, 0xbc, 0x48, 0x38, 0x18, 0x62, 0x74,
	0x37, 0xd1, 0x8b, 0x67, 0x09, 0x07, 0x42, 0x02, 0xa6, 0x47, 0x2f, 0x9b, 0xb2, 0x9d, 0xc0, 0x44,
	0xb6, 0xad, 0x6d, 0x89, 0xfa, 0x6d, 0x3c, 0xf9, 0x39, 0x0d, 0xe5, 0x25, 0x78, 0x6a, 0x9f, 0xdf,
	0x33, 0xd3, 0x79, 0x9a, 0x81, 0x9e, 0xb4, 0x94, 0x15, 0xa6, 0x2c, 0xa5, 0x56, 0xa9, 0x75, 0x26,
	0x18, 0x5e, 0x95, 0x96, 0x06, 0x3f, 0x0c, 0x9a, 0xa3, 0x1d, 0xe6, 0x1c, 0x6a, 0x5a, 0x96, 0x98,
	0xb0, 0x3e, 0x1b, 0xb6, 0x45, 0xbc, 0xf3, 0x3e, 0x74, 0x14, 0xfa, 0xc2, 0x91, 0x0d, 0x64, 0x74,
	0x52, 0x89, 0xd6, 0x29, 0xe2, 0x09, 0x34, 0x1d, 0xbe, 0x6f, 0xd0, 0x87, 0xa4, 0x1a, 0xdd, 0x83,
	0xe4, 0xd7, 0xd0, 0xf9, 0x90, 0x14, 0x72, 0x8b, 0x8e, 0x8c, 0x4a, 0x6a, 0x7d, 0x36, 0xac, 0x0b,
	0xd8, 0xa2, 0x97, 0x48, 0xf8, 0x2d, 0xf4, 0xd6, 0xa4, 0xd1, 0xe7, 0xa4, 0x73, 0x87, 0xde, 0x1a,
	0xed, 0x31, 0xa9, 0xc7, 0xb2, 0x8b, 0x68, 0x4c, 0xb4, 0xd8, 0xe3, 0xc1, 0x37, 0x83, 0x86, 0x40,
	0xbf, 0x59, 0x87, 0xd3, 0x89, 0xec, 0xef, 0xc4, 0x27, 0x38, 0x3b, 0xbc, 0x93, 0x17, 0x46, 0x61,
	0xcc, 0x7b, 0xfe, 0x70, 0x99, 0x4a, 0x4b, 0xe9, 0xae, 0x7b, 0x7b, 0x8c, 0x8c, 0x42, 0xf1, 0xff,
	0x50, 0xb9, 0x55, 0xfc, 0x0a, 0x5a, 0xc7, 0x04, 0xbb, 0x6f, 0x1c, 0xf5, 0xe0, 0x06, 0x9a, 0xfb,
	0x26, 0xde, 0x82, 0xda, 0x6c, 0x3e, 0x1b, 0x77, 0xff, 0xf1, 0x06, 0x54, 0xe6, 0xd3, 0x2e, 0xe3,
	0x6d, 0xa8, 0x8f, 0x85, 0x98, 0x8b, 0x6e, 0xe5, 0x39, 0x7d, 0xbd, 0x5b, 0x52, 0x58, 0x6d, 0x16,
	0x69, 0x61, 0xca, 0x6c, 0xea, 0xc8, 0xaf, 0xb4, 0x9c, 0x7c, 0xa1, 0xcb, 0x3e, 0x95, 0x09, 0xf7,
	0x2b, 0x5c, 0x5b, 0x74, 0x99, 0x7d, 0x5b, 0x66, 0x76, 0x21, 0x2d, 0x2d, 0x1a, 0x71, 0x0f, 0x8f,
	0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x4d, 0x4d, 0xdd, 0x5e, 0x9c, 0x01, 0x00, 0x00,
}
