// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/commands.proto

package pbapi // import "github.com/KrishnaIyer/xdot-helper/pkg/pbapi"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Command is equivalent to a single AT command as defined in the XDOT spec.
type Command struct {
	// name is the user defined name of the AT command.
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// description is a simple function description.
	Description string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	// request is the actual request sent to the XDOT.
	Request string `protobuf:"bytes,3,opt,name=request" json:"request,omitempty"`
	// arguments are optional arguments used for some commands.
	Arguments string `protobuf:"bytes,4,opt,name=arguments" json:"arguments,omitempty"`
	// wait_period is the amount of time to wait for a response.
	WaitPeriod int32 `protobuf:"varint,5,opt,name=wait_period,json=waitPeriod" json:"wait_period,omitempty"`
	// lines_in_response is the expected lines in the response for each  command.
	LinesInResponse      int32    `protobuf:"varint,6,opt,name=lines_in_response,json=linesInResponse" json:"lines_in_response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}
func (*Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_commands_bd0c2daae8edb92d, []int{0}
}
func (m *Command) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command.Unmarshal(m, b)
}
func (m *Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command.Marshal(b, m, deterministic)
}
func (dst *Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command.Merge(dst, src)
}
func (m *Command) XXX_Size() int {
	return xxx_messageInfo_Command.Size(m)
}
func (m *Command) XXX_DiscardUnknown() {
	xxx_messageInfo_Command.DiscardUnknown(m)
}

var xxx_messageInfo_Command proto.InternalMessageInfo

func (m *Command) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Command) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Command) GetRequest() string {
	if m != nil {
		return m.Request
	}
	return ""
}

func (m *Command) GetArguments() string {
	if m != nil {
		return m.Arguments
	}
	return ""
}

func (m *Command) GetWaitPeriod() int32 {
	if m != nil {
		return m.WaitPeriod
	}
	return 0
}

func (m *Command) GetLinesInResponse() int32 {
	if m != nil {
		return m.LinesInResponse
	}
	return 0
}

// Response is the response bytes received on the serial port.
type Response struct {
	Response             []byte   `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_commands_bd0c2daae8edb92d, []int{1}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetResponse() []byte {
	if m != nil {
		return m.Response
	}
	return nil
}

func init() {
	proto.RegisterType((*Command)(nil), "api.Command")
	proto.RegisterType((*Response)(nil), "api.Response")
}

func init() { proto.RegisterFile("api/commands.proto", fileDescriptor_commands_bd0c2daae8edb92d) }

var fileDescriptor_commands_bd0c2daae8edb92d = []byte{
	// 245 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0x89, 0xfd, 0x3f, 0x15, 0xc4, 0x39, 0x2d, 0x22, 0x58, 0x7a, 0x90, 0x22, 0x9a, 0x1c,
	0x7c, 0x03, 0x3d, 0x15, 0x2f, 0x92, 0xa3, 0x97, 0xb0, 0x49, 0x86, 0x64, 0xb0, 0xbb, 0x3b, 0xee,
	0x6e, 0x50, 0xdf, 0xcf, 0x07, 0x93, 0xae, 0xb6, 0x7a, 0xfb, 0xbe, 0xdf, 0xef, 0xbb, 0xcc, 0x00,
	0x6a, 0xe1, 0xa2, 0x71, 0xc6, 0x68, 0xdb, 0x86, 0x5c, 0xbc, 0x8b, 0x0e, 0x47, 0x5a, 0x78, 0xfd,
	0x95, 0xc1, 0xec, 0xf1, 0x87, 0x23, 0xc2, 0xd8, 0x6a, 0x43, 0x2a, 0x5b, 0x65, 0x9b, 0x45, 0x99,
	0x32, 0xae, 0x60, 0xd9, 0x52, 0x68, 0x3c, 0x4b, 0x64, 0x67, 0xd5, 0x49, 0x52, 0xff, 0x11, 0x2a,
	0x98, 0x79, 0x7a, 0x1b, 0x28, 0x44, 0x35, 0x4a, 0xf6, 0x50, 0xf1, 0x12, 0x16, 0xda, 0x77, 0x83,
	0x21, 0x1b, 0x83, 0x1a, 0x27, 0xf7, 0x07, 0xf0, 0x0a, 0x96, 0xef, 0x9a, 0x63, 0x25, 0xe4, 0xd9,
	0xb5, 0x6a, 0xb2, 0xca, 0x36, 0x93, 0x12, 0xf6, 0xe8, 0x39, 0x11, 0xbc, 0x81, 0xf3, 0x1d, 0x5b,
	0x0a, 0x15, 0xdb, 0xca, 0x53, 0x10, 0x67, 0x03, 0xa9, 0x69, 0x9a, 0x9d, 0x25, 0xb1, 0xb5, 0xe5,
	0x2f, 0x5e, 0x5f, 0xc3, 0xfc, 0x90, 0xf1, 0x02, 0xe6, 0xc7, 0xf9, 0xfe, 0x94, 0xd3, 0xf2, 0xd8,
	0x1f, 0xf2, 0x97, 0xdb, 0x8e, 0x63, 0x3f, 0xd4, 0x79, 0xe3, 0x4c, 0xf1, 0xe4, 0x39, 0xf4, 0x56,
	0x6f, 0x3f, 0xc9, 0x17, 0x1f, 0xad, 0x8b, 0x77, 0x3d, 0xed, 0x84, 0x7c, 0x21, 0xaf, 0x5d, 0x21,
	0xb5, 0x16, 0xae, 0xa7, 0xe9, 0x55, 0xf7, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x1d, 0x10, 0x13,
	0x56, 0x40, 0x01, 0x00, 0x00,
}
